{% set version = "1.92.0" %}
{% set build = 0 %}
{% set mpi_label = mpi|replace("-devel", "") %}

package:
  name: libboost-mpi
  version: {{ version }}

source:
  url: https://archives.boost.io/release/{{ version }}/source/boost_{{ version|replace(".", "_") }}.tar.gz
  sha256: c4a3b310ddd2472416e091067166b0713be97c63f38c212c484ada022fd296ce
  patches:
    - 5eff1ecc8413b0dc93a1ab047d7fed751e6cb40e.patch  # [not win]

build:
  number: {{ build }}
  string: mpi_{{ mpi_label }}_h{{ PKG_HASH }}_{{ build }}
  run_exports:
    - libboost-mpi

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}

  host:
    - libboost-devel {{ version }}.*
    - {{ mpi }}

  run_constrained:
    - libboost {{ version }}.*

test:
  commands:
    # Verify library
    - test ! -f $PREFIX/lib/libboost_mpi.a                                               # [unix]
    - test -f $PREFIX/lib/libboost_mpi.dylib                                             # [osx]
    - test -f $PREFIX/lib/libboost_mpi.so                                                # [linux]
    - if not exist %PREFIX%\\Library\\bin\\boost_mpi.dll exit 1                          # [win]
    - if not exist %PREFIX%\\Library\\lib\\boost_mpi.lib exit 1                          # [win]
    - if exist %PREFIX%\\Library\\lib\\libboost_mpi.lib exit 1                           # [win]

about:
  home: http://www.boost.org/
  license: BSL-1.0
  license_file: LICENSE_1_0.txt
  summary: Free peer-reviewed portable C++ source libraries.

extra:
  recipe-maintainers:
    - sdebionne
